modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"

  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"

  http_get_2xx:
    prober: http
    http:
      method: GET
      preferred_ip_protocol: "ip4"
  
  tcp_connect:
    prober: tcp
    icmp:
      preferred_ip_protocol: "ip4"

  icmp_ttl5:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
      ttl: 5